Server:
  Functions:
    DisplayDamage:
      enable: true
    DisplayPlayerHealth:
      enable: true
    DisplayPlayerLevel:
      enable: true
Player:
  Functions:
    DisplayDamage:
    DisplayPlayerHealth:
    DisplayPlayerLevel:
